### ISSUE TITLE
关于汉化的问题。

### ISSUE THREAD

**Issue by dreampeng** [mago960806/latale-tools#1]
我现在进入韩服游戏，体验了一下市面上免费汉化。都是带蠕虫病毒的。 想自己研究一个。   不知道大佬清楚相关接口或方法没。有什么指教没有  或者 说 指点指点。希望重新加大佬Q聊一下

**Comment by mago960806** [comment]
因为汉化的原理是替换客户端资源，自然是需要对客户端程序进行一些劫持和内存修改。被防病毒软件检测到异常也属于`正常`情况。即使你自己研究，应该也是一样的结果。

**Comment by dreampeng** [comment]
防病毒软件检测到异常 这个我清楚，但是他们里面嵌入了一个xred蠕虫病毒在里面，把我所有exe和excel都感染了。然后他们收费版是不存在这个得，而且免费版大小基本在200M以上（我看了一下他们是吧里面的spf翻译之后放到其中一个spf重载进去的），  收费版就只有小小的一个10M，exe。  我就很好奇他们这个10M的exe怎么去实现翻译的。   怎么劫持到并修改的？希望能加个大佬微信、qq

**Comment by mago960806** [comment]
915994204，不过你至少要会dll注入和内存调试之类的才能搞。
